/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Schema
         * @description Shape reference for the SSE routes. Always empty; the schema is the point.
         */
        get: operations["event_schema_schema_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        /** Add Source */
        post: operations["add_source_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Source */
        delete: operations["remove_source_sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan */
        post: operations["rescan_sources__source_id__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__doc_id__get"];
        put?: never;
        post?: never;
        /** Remove Document */
        delete: operations["remove_document_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_documents__doc_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild */
        post: operations["rebuild_index_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Jobs */
        get: operations["stream_jobs_jobs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{query_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Query */
        post: operations["cancel_query_query__query_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_chats_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_chats_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_chats_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_chats_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_chats_projects__project_id__patch"];
        trace?: never;
    };
    "/chats/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_chats__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_chats__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_chats__session_id__patch"];
        trace?: never;
    };
    "/chats/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_chats__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["update_connection_connections__connection_id__patch"];
        trace?: never;
    };
    "/connections/{connection_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate */
        post: operations["activate_connections__connection_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description A real probe. Reachability is the thing users actually get wrong.
         */
        post: operations["test_connection_connections_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory */
        get: operations["inventory_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hardware
         * @description What the Rust shell measured and handed over at spawn time.
         */
        get: operations["hardware_models_hardware_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/hub/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hub Search */
        get: operations["hub_search_models_hub_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/hub/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hub Recommended */
        get: operations["hub_recommended_models_hub_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/hub/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hub Detail */
        get: operations["hub_detail_models_hub__repo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download */
        post: operations["download_models_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Model */
        post: operations["activate_model_models__model_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Model */
        delete: operations["remove_model_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_settings_patch"];
        trace?: never;
    };
    "/settings/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe */
        post: operations["wipe_settings_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_eval_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Eval */
        post: operations["run_eval_eval_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettings */
        AppSettings: {
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
            /** Storage Path */
            storage_path: string;
            /** Active Connection Id */
            active_connection_id?: string | null;
            /**
             * Telemetry
             * @default false
             */
            telemetry: boolean;
            retrieval?: components["schemas"]["RetrievalSettings"];
            performance?: components["schemas"]["PerformanceSettings"];
        };
        /** AppSettingsPatch */
        AppSettingsPatch: {
            /** Onboarded */
            onboarded?: boolean | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Active Connection Id */
            active_connection_id?: string | null;
            /** Telemetry */
            telemetry?: boolean | null;
            retrieval?: components["schemas"]["RetrievalSettings"] | null;
            performance?: components["schemas"]["PerformanceSettings"] | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
            /** Mode */
            mode?: ("local" | "global") | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Chunks */
            chunks?: components["schemas"]["RetrievedChunk"][];
            /** Grounding */
            grounding?: ("ok" | "low" | "none") | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatProject */
        ChatProject: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChatProjectCreate */
        ChatProjectCreate: {
            /** Name */
            name: string;
        };
        /** ChatProjectPatch */
        ChatProjectPatch: {
            /** Name */
            name?: string | null;
            /** Pinned */
            pinned?: boolean | null;
        };
        /** ChatSession */
        ChatSession: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Message Count */
            message_count: number;
            /** Scope Doc Id */
            scope_doc_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChatSessionCreate */
        ChatSessionCreate: {
            /** Title */
            title?: string | null;
            /** Scope Doc Id */
            scope_doc_id?: string | null;
            /** Project Id */
            project_id?: string | null;
        };
        /** ChatSessionPatch */
        ChatSessionPatch: {
            /** Title */
            title?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Pinned */
            pinned?: boolean | null;
        };
        /** Citation */
        Citation: {
            /**
             * Marker
             * @description The literal "[doc:page]" the model wrote.
             */
            marker: string;
            /** Doc Id */
            doc_id: string;
            /** Doc Title */
            doc_title: string;
            /** Page */
            page: number;
            /** Chunk Id */
            chunk_id: string;
            /** Section Path */
            section_path?: string | null;
            /** Snippet */
            snippet: string;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** CitationsEvent */
        CitationsEvent: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
            /**
             * Grounding
             * @default ok
             * @enum {string}
             */
            grounding: "ok" | "low" | "none";
        };
        /** Connection */
        Connection: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "openai-compatible" | "anthropic" | "local-inapp";
            /** Base Url */
            base_url?: string | null;
            /** Model Id */
            model_id: string;
            /** Context Window */
            context_window: number;
            /** Max Output Tokens */
            max_output_tokens: number;
            /**
             * Thinking
             * @enum {string}
             */
            thinking: "off" | "low" | "medium" | "high";
            /** Is Remote */
            is_remote: boolean;
            /** Has Api Key */
            has_api_key: boolean;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConnectionInput */
        ConnectionInput: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "openai-compatible" | "anthropic" | "local-inapp";
            /** Base Url */
            base_url?: string | null;
            /** Model Id */
            model_id: string;
            /**
             * Context Window
             * @default 8192
             */
            context_window: number;
            /**
             * Max Output Tokens
             * @default 1024
             */
            max_output_tokens: number;
            /**
             * Thinking
             * @default off
             * @enum {string}
             */
            thinking: "off" | "low" | "medium" | "high";
            /**
             * Is Remote
             * @default true
             */
            is_remote: boolean;
            /**
             * Api Key
             * @description Write-only. Stored in the OS keychain by the Rust shell, never here.
             */
            api_key?: string | null;
        };
        /** ConnectionTestRequest */
        ConnectionTestRequest: {
            /** Connection Id */
            connection_id?: string | null;
            /** Kind */
            kind?: ("openai-compatible" | "anthropic" | "local-inapp") | null;
            /** Base Url */
            base_url?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Api Key */
            api_key?: string | null;
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            /** Ok */
            ok: boolean;
            /** Reachable */
            reachable: boolean;
            /** Model Found */
            model_found: boolean;
            /** Streaming */
            streaming: boolean;
            /** Tokens Per Second */
            tokens_per_second?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Path */
            path: string;
            /** Title */
            title: string;
            /** Ext */
            ext: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** N Pages */
            n_pages?: number | null;
            /**
             * N Chunks
             * @default 0
             */
            n_chunks: number;
            /** Lang */
            lang?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "parsing" | "ocr" | "chunking" | "embedding" | "indexed" | "error" | "skipped";
            /** Error */
            error?: string | null;
            /** Keywords */
            keywords?: string[];
            /**
             * Mtime
             * Format: date-time
             */
            mtime: string;
            /** Indexed At */
            indexed_at?: string | null;
        };
        /**
         * DocumentChunkRef
         * @description Where a passage sits inside a page, so the reader can highlight it.
         */
        DocumentChunkRef: {
            /** Chunk Id */
            chunk_id: string;
            /** Page */
            page: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Text */
            text: string;
        };
        /** DocumentContent */
        DocumentContent: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Path */
            path: string;
            /** N Pages */
            n_pages: number;
            /** Pages */
            pages: components["schemas"]["DocumentPage"][];
            /** Chunks */
            chunks: components["schemas"]["DocumentChunkRef"][];
        };
        /** DocumentList */
        DocumentList: {
            /** Items */
            items: components["schemas"]["Document"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Page */
            page: number;
            /** Section Path */
            section_path?: string | null;
            /** Text */
            text: string;
        };
        /** DoneEvent */
        DoneEvent: {
            /** Message Id */
            message_id: string;
            latency: components["schemas"]["StageLatency"];
            /** Connection Id */
            connection_id?: string | null;
            /**
             * Remote
             * @default false
             */
            remote: boolean;
        };
        /** DownloadRequest */
        DownloadRequest: {
            /** Repo Id */
            repo_id: string;
            /** Filename */
            filename: string;
            /**
             * Role
             * @enum {string}
             */
            role: "embedding" | "reranking" | "generation";
            /**
             * Activate
             * @default false
             */
            activate: boolean;
            /**
             * Accept Reindex
             * @default false
             */
            accept_reindex: boolean;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** EvalMetrics */
        EvalMetrics: {
            /** Set Name */
            set_name: string;
            /** N Questions */
            n_questions: number;
            /** Recall At 1 */
            recall_at_1: number;
            /** Recall At 6 */
            recall_at_6: number;
            /** Mrr */
            mrr: number;
            /** Ndcg At 6 */
            ndcg_at_6: number;
            latency_p50: components["schemas"]["StageLatency"];
            latency_p95: components["schemas"]["StageLatency"];
            /** Baseline Recall At 6 */
            baseline_recall_at_6?: number | null;
        };
        /** EvalProgressEvent */
        EvalProgressEvent: {
            /** Completed */
            completed: number;
            /** Total */
            total: number;
            /** Question */
            question: string;
        };
        /** EvalQuestionResult */
        EvalQuestionResult: {
            /** Q */
            q: string;
            /**
             * Type
             * @enum {string}
             */
            type: "local" | "global";
            /** Hit */
            hit: boolean;
            /** Rank */
            rank?: number | null;
            /**
             * Ndcg
             * @default 0
             */
            ndcg: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** EvalResult */
        EvalResult: {
            metrics: components["schemas"]["EvalMetrics"];
            /** Questions */
            questions: components["schemas"]["EvalQuestionResult"][];
        };
        /** EvalRunRequest */
        EvalRunRequest: {
            /**
             * Set Name
             * @default base
             */
            set_name: string;
            /** Connection Id */
            connection_id?: string | null;
            /**
             * Compare Baseline
             * @default true
             */
            compare_baseline: boolean;
        };
        /** EvalSet */
        EvalSet: {
            /** Name */
            name: string;
            /** N Questions */
            n_questions: number;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareInfo */
        HardwareInfo: {
            /** Os */
            os: string;
            /** Arch */
            arch: string;
            /** Cpu Count */
            cpu_count: number;
            /** Ram Mb */
            ram_mb: number;
            /** Vram Mb */
            vram_mb: number;
            /**
             * Gpu Backend
             * @enum {string}
             */
            gpu_backend: "metal" | "cuda" | "vulkan" | "cpu";
            /** Gpu Name */
            gpu_name?: string | null;
            /**
             * Profile
             * @enum {string}
             */
            profile: "cpu" | "balanced" | "gpu";
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "starting" | "error";
            /** Version */
            version: string;
            /** Dev Mode */
            dev_mode: boolean;
            /** Uptime S */
            uptime_s: number;
            /**
             * Stub
             * @description True while the core is serving fixture data.
             */
            stub: boolean;
            /** Processes */
            processes: components["schemas"]["ProcessStatus"][];
            index: components["schemas"]["IndexStats"];
            /** Models Ready */
            models_ready: boolean;
        };
        /** HubFile */
        HubFile: {
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
            /** Quant */
            quant?: string | null;
            /**
             * Fit
             * @default unknown
             * @enum {string}
             */
            fit: "vram" | "ram" | "too-large" | "unknown";
            /** Fit Note */
            fit_note?: string | null;
        };
        /** HubModel */
        HubModel: {
            /** Id */
            id: string;
            /** Author */
            author?: string | null;
            /** Name */
            name: string;
            /**
             * Downloads
             * @default 0
             */
            downloads: number;
            /**
             * Likes
             * @default 0
             */
            likes: number;
            /**
             * Trending Score
             * @default 0
             */
            trending_score: number;
            /** Pipeline Tag */
            pipeline_tag?: string | null;
            /** License */
            license?: string | null;
            /** Tags */
            tags?: string[];
            /** Updated At */
            updated_at?: string | null;
            /**
             * Gguf
             * @default false
             */
            gguf: boolean;
            /**
             * Recommended
             * @default false
             */
            recommended: boolean;
            /** Recommended Reason */
            recommended_reason?: string | null;
        };
        /** HubModelDetail */
        HubModelDetail: {
            model: components["schemas"]["HubModel"];
            /** Files */
            files: components["schemas"]["HubFile"][];
            /** Readme Excerpt */
            readme_excerpt?: string | null;
        };
        /** HubSearchResult */
        HubSearchResult: {
            /** Items */
            items: components["schemas"]["HubModel"][];
            /** Role */
            role?: ("embedding" | "reranking" | "generation") | null;
            /** Query */
            query?: string | null;
        };
        /** IndexStats */
        IndexStats: {
            /**
             * Documents
             * @default 0
             */
            documents: number;
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /**
             * Parents
             * @default 0
             */
            parents: number;
            /**
             * Topics
             * @default 0
             */
            topics: number;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Embed Model */
            embed_model: string;
            /** Embed Dim */
            embed_dim: number;
            /** Reranker Model */
            reranker_model: string;
            /** Schema Version */
            schema_version: number;
            /** Last Indexed At */
            last_indexed_at?: string | null;
        };
        /** InstalledModel */
        InstalledModel: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "embedding" | "reranking" | "generation";
            /** Name */
            name: string;
            /** Repo Id */
            repo_id: string;
            /** Filename */
            filename: string;
            /** Quant */
            quant?: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256?: string | null;
            /** Active */
            active: boolean;
            /** Shipped */
            shipped: boolean;
            /** Downloaded At */
            downloaded_at?: string | null;
            /** Context Length */
            context_length?: number | null;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "index" | "reindex" | "remove" | "download" | "recluster" | "eval";
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "error" | "cancelled";
            /** Label */
            label: string;
            /** Detail */
            detail?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /** Total */
            total?: number | null;
            /** Error */
            error?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** ModeEvent */
        ModeEvent: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "local" | "global";
            /** Reason */
            reason: string;
            /** Scope */
            scope?: string | null;
        };
        /** ModelInventory */
        ModelInventory: {
            /** Installed */
            installed: components["schemas"]["InstalledModel"][];
            /** Active Embedding */
            active_embedding?: string | null;
            /** Active Reranking */
            active_reranking?: string | null;
            /** Active Generation */
            active_generation?: string | null;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** PerformanceSettings */
        PerformanceSettings: {
            /**
             * Profile
             * @default balanced
             * @enum {string}
             */
            profile: "cpu" | "balanced" | "gpu";
            /**
             * Embed Batch
             * @default 32
             */
            embed_batch: number;
            /**
             * Gpu Layers
             * @default 999
             */
            gpu_layers: number;
            /**
             * Max Parallel Parsers
             * @default 4
             */
            max_parallel_parsers: number;
        };
        /** ProcessStatus */
        ProcessStatus: {
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ragcore" | "embedding" | "reranking" | "generation";
            /**
             * State
             * @enum {string}
             */
            state: "stopped" | "starting" | "ready" | "restarting" | "error";
            /** Pid */
            pid?: number | null;
            /** Port */
            port?: number | null;
            /**
             * Uptime S
             * @default 0
             */
            uptime_s: number;
            /**
             * Restarts
             * @default 0
             */
            restarts: number;
            /** Detail */
            detail?: string | null;
        };
        /** QueryFilters */
        QueryFilters: {
            /** Source Ids */
            source_ids?: string[] | null;
            /** Doc Ids */
            doc_ids?: string[] | null;
            /** Exts */
            exts?: string[] | null;
            /** Langs */
            langs?: string[] | null;
            /** After */
            after?: string | null;
            /** Before */
            before?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Q */
            q: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Query Id
             * @description Client-generated, so cancellation works before the first frame arrives.
             */
            query_id?: string | null;
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "local" | "global";
            /** Connection Id */
            connection_id?: string | null;
            filters?: components["schemas"]["QueryFilters"];
        };
        /** ReindexRequest */
        ReindexRequest: {
            /** Source Id */
            source_id?: string | null;
            /** Doc Ids */
            doc_ids?: string[] | null;
            /**
             * Full
             * @default false
             */
            full: boolean;
        };
        /** RetrievalSettings */
        RetrievalSettings: {
            /**
             * Dense Top K
             * @default 40
             */
            dense_top_k: number;
            /**
             * Bm25 Top K
             * @default 40
             */
            bm25_top_k: number;
            /**
             * Rrf K
             * @default 60
             */
            rrf_k: number;
            /**
             * Rerank Candidates
             * @default 40
             */
            rerank_candidates: number;
            /**
             * Top K
             * @default 6
             */
            top_k: number;
            /**
             * Min Score
             * @default 0.3
             */
            min_score: number;
            /**
             * Context Token Budget
             * @default 4096
             */
            context_token_budget: number;
            /**
             * History Token Budget
             * @default 2048
             */
            history_token_budget: number;
        };
        /** RetrievedChunk */
        RetrievedChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Doc Title */
            doc_title: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Section Path */
            section_path?: string | null;
            /** Text */
            text: string;
            /** Dense Rank */
            dense_rank?: number | null;
            /** Bm25 Rank */
            bm25_rank?: number | null;
            /**
             * Rrf Score
             * @default 0
             */
            rrf_score: number;
            /**
             * Rerank Score
             * @default 0
             */
            rerank_score: number;
        };
        /** Source */
        Source: {
            /** Path */
            path: string;
            /** Include Globs */
            include_globs?: string[];
            /** Exclude Globs */
            exclude_globs?: string[];
            /**
             * Max File Mb
             * @default 100
             */
            max_file_mb: number;
            /**
             * Watch
             * @default true
             */
            watch: boolean;
            /** Id */
            id: string;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
            /**
             * Indexed Count
             * @default 0
             */
            indexed_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Last Scan At */
            last_scan_at?: string | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Path */
            path: string;
            /** Include Globs */
            include_globs?: string[];
            /** Exclude Globs */
            exclude_globs?: string[];
            /**
             * Max File Mb
             * @default 100
             */
            max_file_mb: number;
            /**
             * Watch
             * @default true
             */
            watch: boolean;
        };
        /** SourcesEvent */
        SourcesEvent: {
            /** Chunks */
            chunks: components["schemas"]["RetrievedChunk"][];
            /** Candidates */
            candidates: number;
            /** Kept */
            kept: number;
        };
        /** StageLatency */
        StageLatency: {
            /**
             * Embed Ms
             * @default 0
             */
            embed_ms: number;
            /**
             * Dense Ms
             * @default 0
             */
            dense_ms: number;
            /**
             * Bm25 Ms
             * @default 0
             */
            bm25_ms: number;
            /**
             * Rerank Ms
             * @default 0
             */
            rerank_ms: number;
            /**
             * Pack Ms
             * @default 0
             */
            pack_ms: number;
            /**
             * Llm First Token Ms
             * @default 0
             */
            llm_first_token_ms: number;
            /**
             * Total Ms
             * @default 0
             */
            total_ms: number;
        };
        /** StartEvent */
        StartEvent: {
            /** Query Id */
            query_id: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * StreamEnvelope
         * @description Every frame the SSE routes can emit, in one model.
         *
         *     Streaming responses never pass through `response_model`, so without this the
         *     frame shapes would not reach OpenAPI and the UI would be typing them by
         *     hand. `GET /schema/events` returns an empty one; its purpose is the schema.
         */
        StreamEnvelope: {
            start?: components["schemas"]["StartEvent"] | null;
            mode?: components["schemas"]["ModeEvent"] | null;
            sources?: components["schemas"]["SourcesEvent"] | null;
            token?: components["schemas"]["TokenEvent"] | null;
            citations?: components["schemas"]["CitationsEvent"] | null;
            done?: components["schemas"]["DoneEvent"] | null;
            error?: components["schemas"]["ErrorEvent"] | null;
            job?: components["schemas"]["Job"] | null;
            eval_progress?: components["schemas"]["EvalProgressEvent"] | null;
            eval_result?: components["schemas"]["EvalResult"] | null;
        };
        /** TokenEvent */
        TokenEvent: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WipeRequest */
        WipeRequest: {
            /**
             * Confirm
             * @description Must equal "DELETE" for the wipe to run.
             */
            confirm: string;
            /**
             * Keep Connections
             * @default true
             */
            keep_connections: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    event_schema_schema_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEnvelope"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    add_source_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_source_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_sources__source_id__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                status?: ("queued" | "parsing" | "ocr" | "chunking" | "embedding" | "indexed" | "error" | "skipped") | null;
                q?: string | null;
                ext?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_documents__doc_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_index_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReindexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    stream_jobs_jobs_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_query_query__query_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"][];
                };
            };
        };
    };
    create_session_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_chats_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatProject"][];
                };
            };
        };
    };
    create_project_chats_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_chats_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_chats_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_chats__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_chats__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_chats__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_chats__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    create_connection_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_connections__connection_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_connections_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inventory_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInventory"];
                };
            };
        };
    };
    hardware_models_hardware_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareInfo"];
                };
            };
        };
    };
    hub_search_models_hub_search_get: {
        parameters: {
            query?: {
                role?: ("embedding" | "reranking" | "generation") | null;
                q?: string | null;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hub_recommended_models_hub_recommended_get: {
        parameters: {
            query: {
                role: "embedding" | "reranking" | "generation";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hub_detail_models_hub__repo_id__get: {
        parameters: {
            query?: {
                role?: ("embedding" | "reranking" | "generation") | null;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubModelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_models_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_model_models__model_id__activate_post: {
        parameters: {
            query?: {
                accept_reindex?: boolean;
            };
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_model_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    patch_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wipe_settings_wipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WipeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sets_eval_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSet"][];
                };
            };
        };
    };
    run_eval_eval_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
