/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellChatRouteImport } from './routes/_shell.chat'
import { Route as ShellDiagnosticsRouteImport } from './routes/_shell.diagnostics'
import { Route as ShellEvalRouteImport } from './routes/_shell.eval'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellModelsRouteImport } from './routes/_shell.models'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellChatIndexRouteImport } from './routes/_shell.chat.index'
import { Route as ShellChatSessionIdRouteImport } from './routes/_shell.chat.$sessionId'
import { Route as ShellReaderDocIdRouteImport } from './routes/_shell.reader.$docId'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell.settings.index'
import { Route as ShellSettingsSectionRouteImport } from './routes/_shell.settings.$section'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDiagnosticsRoute = ShellDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEvalRoute = ShellEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatIndexRoute = ShellChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellChatRoute,
} as any)
const ShellChatSessionIdRoute = ShellChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ShellChatRoute,
} as any)
const ShellReaderDocIdRoute = ShellReaderDocIdRouteImport.update({
  id: '/reader/$docId',
  path: '/reader/$docId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsSectionRoute = ShellSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ShellSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof ShellChatRouteWithChildren
  '/diagnostics': typeof ShellDiagnosticsRoute
  '/eval': typeof ShellEvalRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/settings': typeof ShellSettingsRouteWithChildren
  '/chat/$sessionId': typeof ShellChatSessionIdRoute
  '/reader/$docId': typeof ShellReaderDocIdRoute
  '/settings/$section': typeof ShellSettingsSectionRoute
  '/chat/': typeof ShellChatIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/diagnostics': typeof ShellDiagnosticsRoute
  '/eval': typeof ShellEvalRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/': typeof ShellIndexRoute
  '/chat/$sessionId': typeof ShellChatSessionIdRoute
  '/reader/$docId': typeof ShellReaderDocIdRoute
  '/settings/$section': typeof ShellSettingsSectionRoute
  '/chat': typeof ShellChatIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_shell/chat': typeof ShellChatRouteWithChildren
  '/_shell/diagnostics': typeof ShellDiagnosticsRoute
  '/_shell/eval': typeof ShellEvalRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/settings': typeof ShellSettingsRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/chat/$sessionId': typeof ShellChatSessionIdRoute
  '/_shell/reader/$docId': typeof ShellReaderDocIdRoute
  '/_shell/settings/$section': typeof ShellSettingsSectionRoute
  '/_shell/chat/': typeof ShellChatIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/chat'
    | '/diagnostics'
    | '/eval'
    | '/library'
    | '/models'
    | '/settings'
    | '/chat/$sessionId'
    | '/reader/$docId'
    | '/settings/$section'
    | '/chat/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/diagnostics'
    | '/eval'
    | '/library'
    | '/models'
    | '/'
    | '/chat/$sessionId'
    | '/reader/$docId'
    | '/settings/$section'
    | '/chat'
    | '/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/onboarding'
    | '/_shell/chat'
    | '/_shell/diagnostics'
    | '/_shell/eval'
    | '/_shell/library'
    | '/_shell/models'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/chat/$sessionId'
    | '/_shell/reader/$docId'
    | '/_shell/settings/$section'
    | '/_shell/chat/'
    | '/_shell/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/diagnostics': {
      id: '/_shell/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof ShellDiagnosticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/eval': {
      id: '/_shell/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof ShellEvalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/': {
      id: '/_shell/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ShellChatIndexRouteImport
      parentRoute: typeof ShellChatRoute
    }
    '/_shell/chat/$sessionId': {
      id: '/_shell/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ShellChatSessionIdRouteImport
      parentRoute: typeof ShellChatRoute
    }
    '/_shell/reader/$docId': {
      id: '/_shell/reader/$docId'
      path: '/reader/$docId'
      fullPath: '/reader/$docId'
      preLoaderRoute: typeof ShellReaderDocIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/$section': {
      id: '/_shell/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof ShellSettingsSectionRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
  }
}

interface ShellChatRouteChildren {
  ShellChatSessionIdRoute: typeof ShellChatSessionIdRoute
  ShellChatIndexRoute: typeof ShellChatIndexRoute
}

const ShellChatRouteChildren: ShellChatRouteChildren = {
  ShellChatSessionIdRoute: ShellChatSessionIdRoute,
  ShellChatIndexRoute: ShellChatIndexRoute,
}

const ShellChatRouteWithChildren = ShellChatRoute._addFileChildren(
  ShellChatRouteChildren,
)

interface ShellSettingsRouteChildren {
  ShellSettingsSectionRoute: typeof ShellSettingsSectionRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellSettingsRouteChildren: ShellSettingsRouteChildren = {
  ShellSettingsSectionRoute: ShellSettingsSectionRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellSettingsRouteWithChildren = ShellSettingsRoute._addFileChildren(
  ShellSettingsRouteChildren,
)

interface ShellRouteChildren {
  ShellChatRoute: typeof ShellChatRouteWithChildren
  ShellDiagnosticsRoute: typeof ShellDiagnosticsRoute
  ShellEvalRoute: typeof ShellEvalRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellSettingsRoute: typeof ShellSettingsRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
  ShellReaderDocIdRoute: typeof ShellReaderDocIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellChatRoute: ShellChatRouteWithChildren,
  ShellDiagnosticsRoute: ShellDiagnosticsRoute,
  ShellEvalRoute: ShellEvalRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellSettingsRoute: ShellSettingsRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
  ShellReaderDocIdRoute: ShellReaderDocIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
